import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css"; // Import here, NOT in nested layouts


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.js (main layout)

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <header>

//         </header>
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
